<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PI-LT-1282L" name="Contacts" tests="1" failures="1" timestamp="18 Jul 2016 05:32:38 GMT" time="20.74" errors="0">
  <testcase name="dialNumber" time="18.778" classname="Contacts.Dialling_number">
    <failure type="java.lang.AssertionError" message="Errrors in dialing expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Errrors in dialing expected [true] but found [false]
	at Contacts.Dialling_number.dialNumber(Dialling_number.java:20)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- dialNumber -->
</testsuite> <!-- Contacts -->
